export const cartImg = {
  position: 'absolute',
  top: '15%',
  left: '79%',
  width: '6%',
  height: '4%',
  backgroundColor: 'rgba(20, 222, 40, 0.4)',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  color: 'white',
  fontSize: '24px',
  zIndex: 1,
  cursor: 'pointer',
  
};
export const goldSaucer = {
    position: 'absolute',
    top: '35.3%',
    left: '17.5%',
    width: '20.4%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
    
  };
  export const madeInHeaven = {
    position: 'absolute',
    top: '38.8%',
    left: '17.5%',
    width: '33.3%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
    
  };
  export const superSonic = {
    position: 'absolute',
    top: '41.7%',
    left: '17.5%',
    width: '26%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
    
  };
  export const psychoCrusher = {
    position: 'absolute',
    top: '44.9%',
    left: '17.5%',
    width: '29.6%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const yoshiIsland = {
    position: 'absolute',
    top: '47.9%',
    left: '17.5%',
    width: '21%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const loveIsBlue = {
    position: 'absolute',
    top: '51.6%',
    left: '17.5%',
    width: '21%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const mojito = {
    position: 'absolute',
    top: '34.4%',
    left: '54.4%',
    width: '23.4%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const margarita = {
    position: 'absolute',
    top: '38%',
    left: '54.4%',
    width: '24%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const sexOnTheBeach = {
    position: 'absolute',
    top: '40.6%',
    left: '54.4%',
    width: '24%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const tequilaSunrise = {
    position: 'absolute',
    top: '44.1%',
    left: '54.4%',
    width: '22%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const longIslandIcedTea = {
    position: 'absolute',
    top: '46.7%',
    left: '54.4%',
    width: '28.2%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const uptownMule = {
    position: 'absolute',
    top: '50%',
    left: '54.4%',
    width: '24%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const amarettoSour = {
    position: 'absolute',
    top: '53.1%',
    left: '54.4%',
    width: '24%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const pinaColada = {
    position: 'absolute',
    top: '56%',
    left: '54.4%',
    width: '23%',
    height: '2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
// Customer can choose a drink to be made- check box liquor, ice not ice
export const regularCockTails = {
    position: 'absolute',
    top: '30.5%',
    left: '54.4%',
    width: '22%',
    height: '3.2%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
   // Non-Alcoholic - scroll through non-alcholic cocktails
  export const nonAlcoholicBev = {
    position: 'absolute',
    top: '55.5%',
    left: '17.5%',
    width: '22%',
    height: '2.3%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const oneUpBucket = {
    position: 'absolute',
    top: '58.6%',
    left: '17.6%',
    width: '27%',
    height: '6%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const onDraft = {
    position: 'absolute',
    top: '66.5%',
    left: '17.6%',
    width: '27%',
    height: '9.5%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const canBottle = {
    position: 'absolute',
    top: '66.5%',
    left: '52%',
    width: '30%',
    height: '9.5%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const fountainDrinks = {
    position: 'absolute',
    top: '79.5%',
    left: '17.6%',
    width: '30.5%',
    height: '2.5%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const redBull = {
    position: 'absolute',
    top: '79.5%',
    left: '55.6%',
    width: '27%',
    height: '2.5%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const bigDrinks = {
    position: 'absolute',
    top: '58.9%',
    left: '53%',
    width: '30.5%',
    height: '6.5%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };
  export const hookah = {
    position: 'absolute',
    top: '82.9%',
    left: '40%',
    width: '22%',
    height: '3%',
    backgroundColor: 'rgba(189, 222, 20, 0.4)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    color: 'white',
    fontSize: '24px',
    zIndex: 1,
    cursor: 'pointer',
  };








